apiVersion: v1
kind: Service
metadata:
  name: simple-oath2-server-service
spec:
  selector:
    app: simple-oath2-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer